extends RefCounted
class_name LocalAgentsWorldRuntimeDemoProfileCatalog

static func runtime_profile_settings(profile_id: String) -> Dictionary:
	match profile_id:
		"voxel_destruction_only":
			return {
				"controller": {
					"simulation_ticks_per_second": 4.0,
					"living_profile_push_interval_ticks": 4,
					"visual_environment_update_interval_ticks": 2,
					"hud_refresh_interval_ticks": 1,
					"day_night_cycle_enabled": false,
				},
				"graphics": {
					"transform_stage_a_system_enabled": false,
					"transform_stage_b_system_enabled": false,
					"transform_stage_c_system_enabled": true,
					"transform_stage_d_system_enabled": false,
					"resource_pipeline_enabled": false,
					"structure_lifecycle_enabled": false,
					"culture_cycle_enabled": false,
					"ecology_system_enabled": false,
					"settlement_system_enabled": false,
					"villager_system_enabled": false,
					"cognition_system_enabled": false,
					"smell_gpu_compute_enabled": false,
					"wind_gpu_compute_enabled": false,
					"voxel_gate_smell_enabled": false,
					"voxel_gate_plants_enabled": false,
					"voxel_gate_mammals_enabled": false,
					"voxel_gate_shelter_enabled": false,
					"voxel_gate_profile_refresh_enabled": false,
					"voxel_gate_edible_index_enabled": false,
					"voxel_process_gating_enabled": true,
					"voxel_dynamic_tick_rate_enabled": true,
					"voxel_tick_min_interval_seconds": 0.12,
					"voxel_tick_max_interval_seconds": 0.9,
				},
			}
		"full_sim":
			return {
				"controller": {
					"simulation_ticks_per_second": 4.0,
					"living_profile_push_interval_ticks": 4,
					"visual_environment_update_interval_ticks": 2,
					"hud_refresh_interval_ticks": 1,
					"day_night_cycle_enabled": true,
				},
				"graphics": {
					"water_shader_enabled": true,
					"ocean_surface_enabled": true,
					"river_overlays_enabled": true,
					"rain_post_fx_enabled": true,
					"clouds_enabled": true,
					"cloud_quality": "medium",
					"cloud_density_scale": 0.6,
					"rain_visual_intensity_scale": 0.65,
					"shadows_enabled": true,
					"ssao_enabled": true,
					"glow_enabled": true,
					"simulation_rate_override_enabled": false,
					"simulation_locality_enabled": false,
					"transform_stage_a_solver_decimation_enabled": false,
					"transform_stage_b_solver_decimation_enabled": false,
					"transform_stage_c_solver_decimation_enabled": false,
					"transform_stage_d_solver_decimation_enabled": false,
					"resource_pipeline_decimation_enabled": false,
					"structure_lifecycle_decimation_enabled": false,
					"culture_cycle_decimation_enabled": false,
					"ecology_step_decimation_enabled": false,
				},
			}
		"lightweight_demo":
			return {
				"controller": {
					"simulation_ticks_per_second": 4.0,
					"living_profile_push_interval_ticks": 8,
					"visual_environment_update_interval_ticks": 8,
					"hud_refresh_interval_ticks": 4,
					"day_night_cycle_enabled": false,
				},
				"graphics": {
					"water_shader_enabled": false,
					"ocean_surface_enabled": false,
					"river_overlays_enabled": false,
					"rain_post_fx_enabled": false,
					"clouds_enabled": false,
					"shadows_enabled": false,
					"ssr_enabled": false,
					"ssao_enabled": false,
					"ssil_enabled": false,
					"sdfgi_enabled": false,
					"glow_enabled": false,
					"fog_enabled": false,
					"volumetric_fog_enabled": false,
					"simulation_rate_override_enabled": true,
					"simulation_ticks_per_second_override": 2.0,
					"simulation_locality_enabled": true,
					"simulation_locality_dynamic_enabled": true,
					"simulation_locality_radius_tiles": 1,
					"transform_stage_a_solver_decimation_enabled": true,
					"transform_stage_b_solver_decimation_enabled": true,
					"transform_stage_c_solver_decimation_enabled": true,
					"transform_stage_d_solver_decimation_enabled": true,
					"resource_pipeline_decimation_enabled": true,
					"structure_lifecycle_decimation_enabled": true,
					"culture_cycle_decimation_enabled": true,
					"transform_stage_a_texture_upload_decimation_enabled": true,
					"transform_stage_b_texture_upload_decimation_enabled": true,
					"transform_stage_d_texture_upload_decimation_enabled": true,
					"texture_upload_interval_ticks": 12,
					"texture_upload_budget_texels": 2048,
					"ecology_step_decimation_enabled": true,
					"ecology_step_interval_seconds": 0.35,
					"smell_gpu_compute_enabled": false,
					"wind_gpu_compute_enabled": false,
					"voxel_process_gating_enabled": true,
					"voxel_dynamic_tick_rate_enabled": true,
					"voxel_tick_min_interval_seconds": 0.12,
					"voxel_tick_max_interval_seconds": 0.9,
				},
			}
		_:
			return {
				"graphics": {
					"transform_stage_a_system_enabled": false,
					"transform_stage_b_system_enabled": false,
					"transform_stage_c_system_enabled": false,
					"transform_stage_d_system_enabled": false,
					"resource_pipeline_enabled": false,
					"structure_lifecycle_enabled": false,
					"culture_cycle_enabled": false,
					"ecology_system_enabled": false,
					"settlement_system_enabled": false,
					"villager_system_enabled": false,
					"cognition_system_enabled": false,
					"simulation_rate_override_enabled": true,
					"simulation_ticks_per_second_override": 2.0,
				},
			}
