#!/usr/bin/env bash
# Gate: the demo catalogue in addons/local_agents/examples/demos/ must describe every demo, exactly once.
#
# Why this exists: the launcher used to hold a hardcoded array of res:// strings, and the README and
# docs/USAGE.md each held their own copy of the list. All three disagreed, and two demos (TutorialDemo,
# CoreCreatureSmoke) appeared in none of them. The catalogue is now one LocalAgentDemoEntry resource per
# demo, but "drop a file in and it appears" only stays true if forgetting the file is caught here rather
# than by a user noticing a missing row.
#
# WHAT COUNTS AS A DEMO (the rule, applied to the directory rather than a hardcoded list):
#   A .tscn directly in addons/local_agents/examples/ needs a catalogue entry, UNLESS
#     * it is DemoLauncher.tscn. The catalogue viewer is not a rung on its own ladder.
#     * it is a FRAGMENT: some other .tscn in the addon instances it as a PackedScene sub-scene. A
#       fragment belongs to its parent demo, not to the ladder, so it must not get its own row.
#   Entries may point OUTSIDE examples/, as addons/local_agents/game/VoxelWorld.tscn does. Such a
#   scene is still checked for resolution. It is simply never *required* to have an entry.
#
# FAILS WHEN:
#   1. a demo scene (by the rule above) has no entry;
#   2. an entry's `scene` does not resolve to a file on disk;
#   3. two entries share an `order` (their row order would be arbitrary);
#   4. a .tres in demos/ is not a LocalAgentDemoEntry at all;
#   5. addons/local_agents/docs/DEMOS.md is not what the catalogue renders to right now. That page is
#      generated by scripts/gen_demos_doc.sh, and this gate runs its --check mode. Without step 5 the
#      hand-written list drift this gate exists to stop simply comes back through the docs instead.
#
# This parses the .tres files as text rather than booting Godot: it runs in milliseconds and takes no
# editor lock, so it is safe to run alongside scripts/editor_scan.sh.
#
#   scripts/check_demo_catalog.sh            # table + verdict
#   scripts/check_demo_catalog.sh --quiet    # verdict only
# Exit: 0 when the catalogue is consistent, 1 when it is not.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

EXAMPLES_DIR="addons/local_agents/examples"
CATALOG_DIR="$EXAMPLES_DIR/demos"
ENTRY_SCRIPT="res://addons/local_agents/examples/DemoEntry.gd"
# The catalogue viewer itself. Not a demo; everything else in examples/ is, unless it is a fragment.
LAUNCHER="DemoLauncher.tscn"

QUIET=0
if [[ "${1:-}" == "--quiet" ]]; then QUIET=1; fi

if [[ ! -d "$CATALOG_DIR" ]]; then
  echo "check_demo_catalog: FAIL, no catalogue directory at $CATALOG_DIR"
  exit 1
fi

# --- Parse every entry ------------------------------------------------------------------------
# One record per .tres: file|order|scene_path|title|requires_model|requires_voxel|is_entry_resource
# Properties left at their default are OMITTED by Godot when it saves a resource, so every field
# defaults here exactly as it does in DemoEntry.gd rather than being treated as missing.
parse_entry() {
  awk -v entry_script="$ENTRY_SCRIPT" '
    # [ext_resource type="X" uid="uid://y" path="res://z" id="1_a"]
    # The id regex carries a leading space on purpose: a bare /id="/ matches inside uid="..." first
    # (leftmost match), which would read the uid as the resource id on any editor-resaved file.
    /^\[ext_resource/ {
      type=""; path=""; id="";
      if (match($0, /type="[^"]*"/)) type = substr($0, RSTART+6, RLENGTH-7);
      if (match($0, /path="[^"]*"/)) path = substr($0, RSTART+6, RLENGTH-7);
      if (match($0, / id="[^"]*"/))  id   = substr($0, RSTART+5, RLENGTH-6);
      if (id != "") { res_path[id] = path; res_type[id] = type; }
      if (type == "Script" && path == entry_script) is_entry = 1;
      next
    }
    /^order = /  { order = $3; next }
    /^title = "/ { if (match($0, /"[^"]*"/)) title = substr($0, RSTART+1, RLENGTH-2); next }
    # `scene_path = "res://..."` is the current form. The ExtResource branch stays for a .tres still
    # holding a PackedScene reference, so an un-migrated entry is reported rather than read as empty.
    /^scene_path = "/ { if (match($0, /"[^"]*"/)) scene_direct = substr($0, RSTART+1, RLENGTH-2); next }
    /^scene = ExtResource\(/ { if (match($0, /"[^"]*"/)) scene_id = substr($0, RSTART+1, RLENGTH-2); next }
    /^requires_model = /          { model = $3; next }
    /^requires_voxel_backend = /  { voxel = $3; next }
    END {
      if (order == "") order = 0;
      if (model == "") model = "false";
      if (voxel == "") voxel = "false";
      scene = (scene_direct != "") ? scene_direct : ((scene_id == "") ? "" : res_path[scene_id]);
      printf "%s|%s|%s|%s|%s|%s\n", order, scene, title, model, voxel, (is_entry ? "yes" : "no");
    }
  ' "$1"
}

errors=0
rows=""
declare -a orders_seen=()
declare -a scene_paths=()

shopt -s nullglob
tres_files=("$CATALOG_DIR"/*.tres)
shopt -u nullglob

if [[ ${#tres_files[@]} -eq 0 ]]; then
  echo "check_demo_catalog: FAIL, no entries in $CATALOG_DIR"
  exit 1
fi

for tres in "${tres_files[@]}"; do
  record="$(parse_entry "$tres")"
  IFS='|' read -r order scene title model voxel is_entry <<< "$record"
  base="$(basename "$tres")"

  if [[ "$is_entry" != "yes" ]]; then
    echo "  ERROR $base: not a LocalAgentDemoEntry (no ext_resource for $ENTRY_SCRIPT)"
    errors=$((errors + 1))
    continue
  fi

  if [[ -z "$scene" ]]; then
    echo "  ERROR $base: no scene assigned"
    errors=$((errors + 1))
  else
    scene_file="${scene#res://}"
    if [[ ! -f "$scene_file" ]]; then
      echo "  ERROR $base: scene does not resolve: $scene"
      errors=$((errors + 1))
    fi
    scene_paths+=("$scene")
  fi

  for seen in "${orders_seen[@]:-}"; do
    if [[ -n "$seen" && "${seen%%:*}" == "$order" ]]; then
      echo "  ERROR $base: duplicate order $order (also ${seen#*:})"
      errors=$((errors + 1))
    fi
  done
  orders_seen+=("$order:$base")

  flags=""
  [[ "$model" == "true" ]] && flags="${flags}model "
  [[ "$voxel" == "true" ]] && flags="${flags}voxel "
  [[ -z "$flags" ]] && flags="-"
  rows+="$(printf '  %4s  %-26s %-34s %s' "$order" "$base" "$title" "$flags")"$'\n'
done

# --- Every demo scene must be catalogued ---------------------------------------------------------
# Fragment test: is this scene instanced by ANY other .tscn in the addon? Godot always writes the
# path on an ext_resource line (alongside the uid when there is one), so matching the path is enough.
is_fragment() {
  local scene_rel="$1" self="$2"
  grep -rlF "path=\"res://$scene_rel\"" addons/local_agents --include='*.tscn' 2>/dev/null \
    | grep -qv "^$self$"
}

missing=""
for scene_file in "$EXAMPLES_DIR"/*.tscn; do
  base="$(basename "$scene_file")"
  [[ "$base" == "$LAUNCHER" ]] && continue
  if is_fragment "$scene_file" "$scene_file"; then continue; fi
  want="res://$scene_file"
  found=0
  for have in "${scene_paths[@]:-}"; do
    if [[ "$have" == "$want" ]]; then found=1; break; fi
  done
  if [[ "$found" -eq 0 ]]; then
    missing+="  ERROR $base: no catalogue entry, add a .tres in $CATALOG_DIR"$'\n'
    errors=$((errors + 1))
  fi
done
[[ -n "$missing" ]] && printf '%s' "$missing"

# --- The generated demo page must match the catalogue --------------------------------------------
# addons/local_agents/docs/DEMOS.md is rendered from these same .tres files by scripts/gen_demos_doc.sh,
# so checking it here is what stops the old three-copies-of-the-list drift returning through the docs.
GEN_DOC="$ROOT/scripts/gen_demos_doc.sh"
if [[ ! -x "$GEN_DOC" ]]; then
  # Not a silent pass. Three gates in this repo were written, wired into nothing, and reported as
  # delivered (GODOT_BEST_PRACTICES.md, 2026-07-29). A gate that skips its own work when the tool it
  # shells out to is absent or has lost its +x bit is that same failure wearing a different hat.
  echo "  ERROR scripts/gen_demos_doc.sh: missing or not executable, cannot verify docs/DEMOS.md"
  errors=$((errors + 1))
else
  set +e
  doc_out="$("$GEN_DOC" --check 2>&1)"
  rc_doc=$?
  set -e
  if [[ "$rc_doc" -ne 0 ]]; then
    # --quiet asked for a verdict, not a 60-line diff. The last line is the verdict, and it already
    # names the file and the command that fixes it.
    if [[ "$QUIET" -eq 1 ]]; then
      printf '%s\n' "$doc_out" | tail -n 1 | sed 's/^/  /'
    else
      printf '%s\n' "$doc_out" | sed 's/^/  /'
    fi
    errors=$((errors + 1))
  fi
fi

if [[ "$QUIET" -eq 0 && "$errors" -eq 0 ]]; then
  echo "check_demo_catalog: ${#tres_files[@]} entries"
  printf '  %4s  %-26s %-34s %s\n' "ord" "entry" "title" "gated on"
  printf '%s' "$(printf '%s' "$rows" | sort -n)"
  echo ""
fi

if [[ "$errors" -eq 0 ]]; then
  echo "check_demo_catalog: OK (${#tres_files[@]} entries, every examples/*.tscn demo catalogued, docs/DEMOS.md in sync)"
  exit 0
fi
echo "check_demo_catalog: FAIL ($errors error(s))"
exit 1
