#!/usr/bin/env python3
"""Emit the GLSL/gdshader copies of facts whose one declaration is in GDScript.

`--check` regenerates and diffs against the checked-in outputs; non-zero when stale.
"""
import argparse
import ast
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIM = os.path.join(ROOT, "addons", "local_agents", "sim")

REACTION_DEFS = os.path.join(SIM, "material", "reactions", "ReactionDefs.gd")
REACTION_THERMO = os.path.join(SIM, "material", "reactions", "ReactionThermo.gd")
CELL_LIST_PASS = os.path.join(SIM, "material", "sphere_passes", "CellListPass.gd")
REGOLITH = os.path.join(SIM, "material", "MaterialFieldRegolith3D.gd")
RENDER = os.path.join(SIM, "material", "MaterialFieldRender3D.gd")
SPHERE_GRID = os.path.join(SIM, "sphere", "SphereGrid.gd")

GLSLI_OUT = os.path.join(SIM, "material", "kernels3d", "generated.glsli")
SHADERINC_OUT = os.path.join(SIM, "shaders", "generated.gdshaderinc")

BANNER = "// GENERATED by scripts/gen_shared_constants.py. Edit the GDScript source, then regenerate."

SECTIONS = ["Channel slot enum", "Rate models", "Gate bitflags", "Product targets"]


class Missing(Exception):
    pass


def read(path):
    if not os.path.isfile(path):
        raise Missing("source is gone: %s" % path)
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def strip_comment(line):
    return line.split("#", 1)[0].rstrip()


def evaluate(expr, known):
    node = ast.parse(expr.strip(), mode="eval").body
    return _eval(node, known)


def _eval(node, known):
    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
        return node.value
    if isinstance(node, ast.Name):
        if node.id not in known:
            raise Missing("expression names an unknown constant: %s" % node.id)
        return known[node.id]
    if isinstance(node, ast.BinOp):
        left, right = _eval(node.left, known), _eval(node.right, known)
        for kind, fn in ((ast.Add, lambda: left + right), (ast.Sub, lambda: left - right),
                         (ast.Mult, lambda: left * right), (ast.LShift, lambda: left << right),
                         (ast.BitOr, lambda: left | right)):
            if isinstance(node.op, kind):
                return fn()
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return -_eval(node.operand, known)
    raise Missing("expression is not a constant arithmetic form")


def const_int(path, name):
    m = re.search(r"^const %s: int = (.+)$" % re.escape(name), read(path), re.M)
    if not m:
        raise Missing("%s declares no `const %s: int`" % (path, name))
    return int(evaluate(strip_comment(m.group(1)), {}))


def const_float(path, name):
    m = re.search(r"^const %s: float = (.+)$" % re.escape(name), read(path), re.M)
    if not m:
        raise Missing("%s declares no `const %s: float`" % (path, name))
    return float(evaluate(strip_comment(m.group(1)), {}))


def reaction_sections():
    """Every `const NAME: int` of each named `# --- <title>` block of ReactionDefs.gd, in source order."""
    text = read(REACTION_DEFS)
    blocks = re.split(r"^# ---+ *", text, flags=re.M)[1:]
    found, known = {}, {}
    for block in blocks:
        title = block.split("\n", 1)[0]
        for want in SECTIONS:
            if not title.startswith(want):
                continue
            names = []
            for line in block.split("\n"):
                m = re.match(r"^const ([A-Z][A-Z0-9_]*): int = (.+)$", line)
                if not m:
                    continue
                value = int(evaluate(strip_comment(m.group(2)), known))
                known[m.group(1)] = value
                names.append((m.group(1), value))
            found[want] = names
    for want in SECTIONS:
        if not found.get(want):
            raise Missing("ReactionDefs.gd has no non-empty `# --- %s` block" % want)
    return found


def cell_list_flags():
    m = re.search(r"^enum Flag \{(.+?)\}", read(CELL_LIST_PASS), re.M | re.S)
    if not m:
        raise Missing("CellListPass.gd declares no `enum Flag`")
    out = [(n, int(v)) for n, v in re.findall(r"([A-Z][A-Z0-9_]*)\s*=\s*(\d+)", m.group(1))]
    if not out:
        raise Missing("CellListPass.gd's `enum Flag` is empty")
    return out


def face_frames():
    text = read(SPHERE_GRID)
    frames = []
    for name in ("_FACE_N", "_FACE_R", "_FACE_U"):
        m = re.search(r"^const %s: Array\[Vector3\] = \[(.+)\]$" % name, text, re.M)
        if not m:
            raise Missing("SphereGrid.gd declares no `const %s`" % name)
        vecs = re.findall(r"Vector3\(([-0-9.]+),\s*([-0-9.]+),\s*([-0-9.]+)\)", m.group(1))
        if len(vecs) != 6:
            raise Missing("SphereGrid.gd's %s is not six vectors" % name)
        frames.append((name.lstrip("_"), vecs))
    return frames


def glsli_text():
    sections = reaction_sections()
    lines = [BANNER, "", "#ifndef LA_GENERATED_GLSLI", "#define LA_GENERATED_GLSLI", ""]
    lines.append("// reactions/ReactionDefs.gd")
    for want in SECTIONS:
        for name, value in sections[want]:
            lines.append("#define %s %d" % (name, value))
    lines.append("")
    lines.append("// sphere_passes/CellListPass.gd Flag")
    for name, value in cell_list_flags():
        lines.append("#define F_%s %du" % (name, value))
    lines.append("")
    lines.append("// MaterialFieldRegolith3D.gd, reactions/ReactionThermo.gd")
    lines.append("#define REGOLITH_CELLS %d" % const_int(REGOLITH, "REGOLITH_CELLS"))
    lines.append("const float EXP_LIMIT = %s;" % fmt(const_float(REACTION_THERMO, "EXP_LIMIT")))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def fmt(value):
    return repr(float(value))


def shaderinc_text():
    lines = [BANNER, "", "// sphere/SphereGrid.gd cube-face frames; material/MaterialFieldRender3D.gd"]
    for name, vecs in face_frames():
        cells = ", ".join("vec3(%s)" % ", ".join(fmt(float(c)) for c in v) for v in vecs)
        lines.append("const vec3 %s[6] = vec3[6](%s);" % (name, cells))
    lines.append("const int RIPPLE_MAX = %d;" % const_int(RENDER, "RIPPLE_MAX"))
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    try:
        outputs = [(GLSLI_OUT, glsli_text()), (SHADERINC_OUT, shaderinc_text())]
    except (Missing, SyntaxError) as err:
        print("gen_shared_constants: %s" % err, file=sys.stderr)
        return 2
    stale = 0
    for path, want in outputs:
        rel = os.path.relpath(path, ROOT)
        if args.check:
            have = read(path) if os.path.isfile(path) else None
            if have != want:
                print("STALE %s — regenerate with scripts/gen_shared_constants.py" % rel, file=sys.stderr)
                stale = 1
            continue
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(want)
        print("wrote %s" % rel)
    return stale


if __name__ == "__main__":
    sys.exit(main())
